CreateThread(function()
    AddTextEntry('Rog_Release_01', 'Gorilla Face')
    AddTextEntry('Rog_Release_02', 'Snake')
    AddTextEntry('Rog_Release_03', 'Guns & Flags')
    AddTextEntry('Rog_Release_04', 'Centurion')
    AddTextEntry('Rog_Release_05', 'USA')
    AddTextEntry('Rog_Release_06', 'Fire Skull')
    AddTextEntry('Rog_Release_07', 'Hugh')
    AddTextEntry('Rog_Release_08', 'Wrapped in Pride')
    AddTextEntry('Rog_Release_09', 'Scarred')
    AddTextEntry('Rog_Release_10', 'Never Forget')
    AddTextEntry('Rog_Release_11', 'ECG')
    AddTextEntry('Rog_Release_12', 'SAST')
    AddTextEntry('Rog_Release_13', 'LSPD')
    AddTextEntry('Rog_Release_14', 'Caduceus')
    AddTextEntry('Rog_Release_15', 'BCSO')
    AddTextEntry('Rog_Release_16', 'Symbol of Life')
    AddTextEntry('Rog_Release_17', 'Snake of Life')
    AddTextEntry('Rog_Release_18', 'Symbol of Life')
    AddTextEntry('Rog_Release_19', 'LS Medic')
    AddTextEntry('Rog_Release_20', 'Howl')
    AddTextEntry('Rog_Release_21', 'One')
    AddTextEntry('Rog_Release_22', 'Motto')
    AddTextEntry('Rog_Release_23', 'Stripe')
    AddTextEntry('Rog_Release_24', 'USMC')
    AddTextEntry('Rog_Release_25', 'Sparta')
    AddTextEntry('Rog_Release_26', 'American Bravery')
    AddTextEntry('Rog_Release_27', 'Silver Bracelets')
    AddTextEntry('Rog_Release_28', 'K9')
    AddTextEntry('Rog_Release_29', 'Tags')
    AddTextEntry('Rog_Release_30', 'Zip It')
    AddTextEntry('Rog_Release_31', 'Misfits')
    AddTextEntry('Rog_Release_32', 'Ghost')
    AddTextEntry('Rog_Release_35', 'Oilers!')
    AddTextEntry('Rog_Release_36', 'Bs')
end)
